Repository rancher/rke2, pull requests merged in 2021-07, with the labels that each got.

#1311 fix crane cli for windows, add manifest-tool
  .drone.yml
  Makefile
  manifest-runtime.tmpl
  scripts/build-windows-binary
  scripts/build-windows-images
  scripts/package-windows-images
  scripts/publish-manifest-runtime
Labels: area/windows

#1354 add windows docs for rke2
  docs/install/install_options/install_options.md
  docs/install/install_options/windows_agent_config.md
  docs/install/quickstart.md
  docs/install/requirements.md
Labels: area/windows, kind/documentation

#1363 [release-1.21] package windows images after pushing manifest and runtime images
  .drone.yml
Labels: area/windows, kind/bug

#1365 package windows images after pushing runtime manifest/images
  .drone.yml
Labels: area/windows, kind/bug

#1369 use repo.namespace for manifest-tool template
  .drone.yml
  manifest-runtime.tmpl
Labels: kind/bug

#1372 [release 1.21] fix bug, use repo.namespace for manifest-tool template
  .drone.yml
  manifest-runtime.tmpl
Labels: kind/bug

#1377 [release 1.21] hardcode rancher into manifest-tool template
  manifest-runtime.tmpl
Labels: kind/bug

#1374 hardcode rancher namespace for rke2-runtime manifest
  manifest-runtime.tmpl
Labels: kind/bug

#1411 move CI for publishing artifacts to run after windows images
  .drone.yml
Labels: area/windows, kind/bug, priority/critical-urgent

#1413 [release 1.21] move CI for publishing artifacts to run after windows images
  .drone.yml
Labels: area/windows, kind/bug, priority/critical-urgent

#1449 Windows Documentation Update for 1.21.3 release
  docs/install/install_options/install_options.md
  docs/install/install_options/linux_agent_config.md
  docs/install/install_options/windows_agent_config.md
  docs/install/methods.md
  docs/install/quickstart.md
  docs/install/requirements.md
  docs/install/windows_airgap.md
  mkdocs.yml
Labels: area/windows, kind/documentation

#1471 update docs for Windows containers feature
  docs/install/quickstart.md
  docs/install/requirements.md
  docs/install/windows_airgap.md
Labels: area/windows, kind/documentation

#1484 [release 1.21] bump versions in Windows Dockerfile
  Dockerfile.windows
Labels: area/windows

#1480 bump versions in Windows Dockerfile
  Dockerfile.windows
Labels: area/windows

#1488 add Windows RKE2 Uninstall script
  bundle/bin/rke2-uninstall.ps1
Labels: area/windows, enhancement

#1475 Update service watching logic for windows service manager
  go.mod
  go.sum
  pkg/cli/cmds/agent.go
  pkg/cli/cmds/agent_service_windows.go
  pkg/windows/service_linux.go
  pkg/windows/service_windows.go
Labels: area/windows, kind/bug

#1498 [release-1.21] add Windows RKE2 Uninstall script
  bundle/bin/rke2-uninstall.ps1
Labels: area/windows, kind/enhancement
